#!/bin/sh

uci -q get system.@imm_init[0] > "/dev/null" || uci -q add system imm_init > "/dev/null"

if ! uci -q get system.@imm_init[0].lang > "/dev/null"; then
	uci -q set luci.main.lang="auto"
	uci -q commit luci

	uci -q set system.@imm_init[0].lang="1"
	uci -q commit system
fi

if ! uci -q get system.@imm_init[0].anon_mount > "/dev/null"; then
	uci -q set fstab.@global[0].anon_mount="1"
	uci -q commit fstab

	uci -q set system.@imm_init[0].anon_mount="1"
	uci -q commit system
fi

ln -sf "/sbin/ip" "/usr/bin/ip"

sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
echo "DISTRIB_REVISION='R23.11.12'" >> /etc/openwrt_release
#sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
#echo "DISTRIB_DESCRIPTION='OpenWrt v$(date +'%Y.%m.%d') by noodles '" >> /etc/openwrt_release

#sed -i '/luciversion/d' /usr/lib/lua/luci/version.lua
#echo "luciversion = '*noodles*'" >> /usr/lib/lua/luci/version.lua
#sed -i '/luciname/d' /usr/lib/lua/luci/version.lua
#echo "luciname = 'LuCI openwrt-22.03'" >> /usr/lib/lua/luci/version.lua

sed -i "/log-facility/d" "/etc/dnsmasq.conf"
echo "log-facility=/dev/null" >> "/etc/dnsmasq.conf"

rm -f "/tmp/luci-indexcache"
rm -rf "/tmp/luci-modulecache"

exit 0
